#!/bin/sh
#

CNUM=`git log HEAD --pretty=%h|wc -l|tr -d ' '`
echo "$CNUM"
FILE=`cat src/include/version.h | sed "s/COMMITS = \"[0-9]*\"/COMMITS = \"$CNUM\"/"`
echo "$FILE" > src/include/version.h
git add src/include/version.h
unset CNUM
unset FILE